import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { formatBRL } from "@/utils/formatBRL";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
interface Props { tenantId: string; startDate: string; endDate: string; }
export default function ProductProfitabilityReport({ tenantId, startDate, endDate }: Props) {
  const { data, isLoading } = useQuery({ queryKey: ["rpt-product-profit", tenantId, startDate, endDate], queryFn: async () => { const { data } = await supabase.from("product_sales").select("quantity, sale_price_snapshot_cents, purchase_price_snapshot_cents, product:product_id(name)").eq("tenant_id", tenantId).gte("sale_date", startDate).lt("sale_date", endDate); if (!data) return []; const g: Record<string,{name:string;qty:number;revenue:number;cost:number}> = {}; for (const s of data as any[]) { const n = s.product?.name||"—"; if (!g[n]) g[n] = { name: n, qty: 0, revenue: 0, cost: 0 }; g[n].qty += s.quantity; g[n].revenue += s.sale_price_snapshot_cents*s.quantity; g[n].cost += s.purchase_price_snapshot_cents*s.quantity; } return Object.values(g).map(v=>({...v, profit: v.revenue-v.cost, margin: v.revenue>0?((v.revenue-v.cost)/v.revenue*100).toFixed(1):"0"})).sort((a,b)=>b.profit-a.profit); }, enabled: !!tenantId });
  if (isLoading) return <div className="text-sm text-muted-foreground p-4">Carregando...</div>;
  if (!data?.length) return <div className="text-sm text-muted-foreground p-4">Nenhum dado.</div>;
  const chartData = data.slice(0,8).map(d=>({name:d.name.substring(0,12),value:d.profit/100}));
  return (<div className="space-y-6"><div className="bg-card border border-border rounded-2xl p-4 h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`R$${v}`}/><Tooltip/><Bar dataKey="value" fill="hsl(var(--primary))" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="bg-card border border-border rounded-2xl overflow-hidden"><Table><TableHeader><TableRow><TableHead>Produto</TableHead><TableHead className="text-right">Qtd</TableHead><TableHead className="text-right">Receita</TableHead><TableHead className="text-right">Lucro</TableHead><TableHead className="text-right">Margem</TableHead></TableRow></TableHeader><TableBody>{data.map((d,i)=>(<TableRow key={i}><TableCell className="font-medium text-sm">{d.name}</TableCell><TableCell className="text-right">{d.qty}</TableCell><TableCell className="text-right">{formatBRL(d.revenue)}</TableCell><TableCell className="text-right">{formatBRL(d.profit)}</TableCell><TableCell className="text-right">{d.margin}%</TableCell></TableRow>))}</TableBody></Table></div></div>);
}
