import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { formatBRL } from "@/utils/formatBRL";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
interface Props { tenantId: string; startDate: string; endDate: string; }
export default function ServiceProfitabilityReport({ tenantId, startDate, endDate }: Props) {
  const { data, isLoading } = useQuery({ queryKey: ["rpt-service-profit", tenantId, startDate, endDate], queryFn: async () => { const { data } = await supabase.from("booking_items").select("title, total_price_cents, purchase_price_cents, quantity, booking:booking_id(starts_at)").eq("tenant_id", tenantId).eq("type", "service"); if (!data) return []; const filtered = data.filter((i:any)=>{const d=i.booking?.starts_at;return d&&d>=startDate&&d<endDate;}); const g: Record<string,{name:string;revenue:number;cost:number;count:number}> = {}; for (const i of filtered as any[]) { if (!g[i.title]) g[i.title] = { name: i.title, revenue: 0, cost: 0, count: 0 }; g[i.title].revenue += i.total_price_cents; g[i.title].cost += i.purchase_price_cents * i.quantity; g[i.title].count++; } return Object.values(g).map(v=>({...v, profit: v.revenue - v.cost, margin: v.revenue > 0 ? ((v.revenue-v.cost)/v.revenue*100).toFixed(1) : "0" })).sort((a,b)=>b.profit-a.profit); }, enabled: !!tenantId });
  if (isLoading) return <div className="text-sm text-muted-foreground p-4">Carregando...</div>;
  if (!data?.length) return <div className="text-sm text-muted-foreground p-4">Nenhum dado.</div>;
  const chartData = data.slice(0,8).map(d=>({name:d.name.substring(0,12),value:d.profit/100}));
  return (<div className="space-y-6"><div className="bg-card border border-border rounded-2xl p-4 h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`R$${v}`}/><Tooltip/><Bar dataKey="value" fill="hsl(var(--primary))" radius={[6,6,0,0]} name="Lucro"/></BarChart></ResponsiveContainer></div><div className="bg-card border border-border rounded-2xl overflow-hidden"><Table><TableHeader><TableRow><TableHead>Serviço</TableHead><TableHead className="text-right">Qtd</TableHead><TableHead className="text-right">Receita</TableHead><TableHead className="text-right">Lucro</TableHead><TableHead className="text-right">Margem</TableHead></TableRow></TableHeader><TableBody>{data.map((d,i)=>(<TableRow key={i}><TableCell className="font-medium text-sm">{d.name}</TableCell><TableCell className="text-right">{d.count}</TableCell><TableCell className="text-right">{formatBRL(d.revenue)}</TableCell><TableCell className="text-right">{formatBRL(d.profit)}</TableCell><TableCell className="text-right">{d.margin}%</TableCell></TableRow>))}</TableBody></Table></div></div>);
}
