import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { formatBRL } from "@/utils/formatBRL";
import { ExportCSVButton } from "./ExportCSVButton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
interface Props { tenantId: string; startDate: string; endDate: string; }
export default function TopServicesReport({ tenantId, startDate, endDate }: Props) {
  const { data, isLoading } = useQuery({ queryKey: ["rpt-top-services", tenantId, startDate, endDate], queryFn: async () => { const { data } = await supabase.from("bookings").select("service_id, service:service_id(name), booking_items(total_price_cents, type)").eq("tenant_id", tenantId).eq("status", "completed").gte("starts_at", startDate).lt("starts_at", endDate); if (!data) return []; const g: Record<string,{name:string;count:number;total:number}> = {}; for (const b of data) { const s = b.service as any; if (!g[b.service_id]) g[b.service_id] = { name: s?.name||"—", count: 0, total: 0 }; g[b.service_id].count++; g[b.service_id].total += (b.booking_items||[]).filter((i:any)=>i.type==="service").reduce((s:number,i:any)=>s+(i.total_price_cents||0),0); } return Object.values(g).sort((a,b)=>b.count-a.count); }, enabled: !!tenantId });
  if (isLoading) return <div className="text-sm text-muted-foreground p-4">Carregando...</div>;
  if (!data?.length) return <div className="text-sm text-muted-foreground p-4">Nenhum dado.</div>;
  const chartData = data.slice(0,10).map(d=>({name:d.name.substring(0,12),value:d.count}));
  return (<div className="space-y-6"><div className="flex justify-end"><ExportCSVButton data={data.map(d=>({Serviço:d.name,Quantidade:d.count,Faturamento:formatBRL(d.total)}))} columns={[{key:"Serviço",label:"Serviço"},{key:"Quantidade",label:"Qtd"},{key:"Faturamento",label:"Faturamento"}]} filename="servicos-mais-vendidos"/></div><div className="bg-card border border-border rounded-2xl p-4 h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" className="stroke-border"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis/><Tooltip/><Bar dataKey="value" fill="hsl(var(--primary))" radius={[6,6,0,0]} name="Qtd"/></BarChart></ResponsiveContainer></div><div className="bg-card border border-border rounded-2xl overflow-hidden"><Table><TableHeader><TableRow><TableHead>Serviço</TableHead><TableHead className="text-right">Qtd</TableHead><TableHead className="text-right">Faturamento</TableHead></TableRow></TableHeader><TableBody>{data.map((d,i)=>(<TableRow key={i}><TableCell className="font-medium text-sm">{d.name}</TableCell><TableCell className="text-right">{d.count}</TableCell><TableCell className="text-right">{formatBRL(d.total)}</TableCell></TableRow>))}</TableBody></Table></div></div>);
}
